package com.ggsleeper.bean;

// Generated 2017-5-24 9:56:34 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblCarApply generated by hbm2java
 */
@Entity
@Table(name = "tbl_car_apply", catalog = "carmanager")
public class CarApply implements java.io.Serializable {

	private Integer applyId;
	private String carLpn;
	private String carModel;
	private Date godate;
	private Date backdate;
	private String reason;
	private String state;
	private String carDriver;
	private String creatby;
	private String currentreview;
	private Integer reviewnum;

	public CarApply() {
	}

	public CarApply(String carLpn, String carModel, Date godate,
			Date backdate, String reason, String state, String carDriver,
			String creatby, String currentreview, Integer reviewnum) {
		this.carLpn = carLpn;
		this.carModel = carModel;
		this.godate = godate;
		this.backdate = backdate;
		this.reason = reason;
		this.state = state;
		this.carDriver = carDriver;
		this.creatby = creatby;
		this.currentreview = currentreview;
		this.reviewnum = reviewnum;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "apply_id", unique = true, nullable = false)
	public Integer getApplyId() {
		return this.applyId;
	}

	public void setApplyId(Integer applyId) {
		this.applyId = applyId;
	}

	@Column(name = "car_lpn")
	public String getCarLpn() {
		return this.carLpn;
	}

	public void setCarLpn(String carLpn) {
		this.carLpn = carLpn;
	}

	@Column(name = "car_model")
	public String getCarModel() {
		return this.carModel;
	}

	public void setCarModel(String carModel) {
		this.carModel = carModel;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "godate", length = 10)
	public Date getGodate() {
		return this.godate;
	}

	public void setGodate(Date godate) {
		this.godate = godate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "backdate", length = 10)
	public Date getBackdate() {
		return this.backdate;
	}

	public void setBackdate(Date backdate) {
		this.backdate = backdate;
	}

	@Column(name = "reason")
	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	@Column(name = "state")
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "car_driver")
	public String getCarDriver() {
		return this.carDriver;
	}

	public void setCarDriver(String carDriver) {
		this.carDriver = carDriver;
	}

	@Column(name = "creatby")
	public String getCreatby() {
		return this.creatby;
	}

	public void setCreatby(String creatby) {
		this.creatby = creatby;
	}

	@Column(name = "currentreview")
	public String getCurrentreview() {
		return this.currentreview;
	}

	public void setCurrentreview(String currentreview) {
		this.currentreview = currentreview;
	}

	@Column(name = " reviewnum")
	public Integer getReviewnum() {
		return this.reviewnum;
	}

	public void setReviewnum(Integer reviewnum) {
		this.reviewnum = reviewnum;
	}

}
