package com.ggsleeper.bean;

// Generated 2017-4-14 12:24:26 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblCarInfo generated by hbm2java
 */
@Entity
@Table(name = "tbl_car_info", catalog = "carmanager")
public class CarInfo implements java.io.Serializable {

	private Integer infoId;
	private String infoLpn;
	private String infoModel;
	private String infoRecord;
	@Override
	public String toString() {
		return "CarInfo [infoId=" + infoId + ", infoLpn=" + infoLpn
				+ ", infoModel=" + infoModel + ", infoRecord=" + infoRecord
				+ ", infoPlan=" + infoPlan + ", infoCarstate=" + infoCarstate
				+ "]";
	}

	private String infoPlan;
	private String infoCarstate;

	public CarInfo() {
	}

	public CarInfo(String infoLpn, String infoModel, String infoRecord,
			String infoPlan, String infoCarstate) {
		this.infoLpn = infoLpn;
		this.infoModel = infoModel;
		this.infoRecord = infoRecord;
		this.infoPlan = infoPlan;
		this.infoCarstate = infoCarstate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "info_id", unique = true, nullable = false)
	public Integer getInfoId() {
		return this.infoId;
	}

	public void setInfoId(Integer infoId) {
		this.infoId = infoId;
	}

	@Column(name = "info_lpn")
	public String getInfoLpn() {
		return this.infoLpn;
	}

	public void setInfoLpn(String infoLpn) {
		this.infoLpn = infoLpn;
	}

	@Column(name = "info_model")
	public String getInfoModel() {
		return this.infoModel;
	}

	public void setInfoModel(String infoModel) {
		this.infoModel = infoModel;
	}

	@Column(name = "info_record")
	public String getInfoRecord() {
		return this.infoRecord;
	}

	public void setInfoRecord(String infoRecord) {
		this.infoRecord = infoRecord;
	}

	@Column(name = "info_plan")
	public String getInfoPlan() {
		return this.infoPlan;
	}

	public void setInfoPlan(String infoPlan) {
		this.infoPlan = infoPlan;
	}

	@Column(name = "info_carstate")
	public String getInfoCarstate() {
		return this.infoCarstate;
	}

	public void setInfoCarstate(String infoCarstate) {
		this.infoCarstate = infoCarstate;
	}

}
