package com.ggsleeper.bean;

// Generated 2017-5-24 11:17:23 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblDriverInfo generated by hbm2java
 */
@Entity
@Table(name = "tbl_driver_info", catalog = "carmanager")
public class DriverInfo implements java.io.Serializable {

	private Integer driverInfoId;
	private String driverName;
	private String driverAge;
	private String driverType;
	private String driverGrade;
	private String driverState;
	private String driverNotice;
	private Integer driverTel;

	public DriverInfo() {
	}

	public DriverInfo(String driverName, String driverAge,
			String driverType, String driverGrade, String driverState,
			String driverNotice, Integer driverTel) {
		this.driverName = driverName;
		this.driverAge = driverAge;
		this.driverType = driverType;
		this.driverGrade = driverGrade;
		this.driverState = driverState;
		this.driverNotice = driverNotice;
		this.driverTel = driverTel;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "driver_info_id", unique = true, nullable = false)
	public Integer getDriverInfoId() {
		return this.driverInfoId;
	}

	public void setDriverInfoId(Integer driverInfoId) {
		this.driverInfoId = driverInfoId;
	}

	@Column(name = "driver_name")
	public String getDriverName() {
		return this.driverName;
	}

	public void setDriverName(String driverName) {
		this.driverName = driverName;
	}

	@Column(name = "driver_age")
	public String getDriverAge() {
		return this.driverAge;
	}

	public void setDriverAge(String driverAge) {
		this.driverAge = driverAge;
	}

	@Column(name = "driver_type")
	public String getDriverType() {
		return this.driverType;
	}

	public void setDriverType(String driverType) {
		this.driverType = driverType;
	}

	@Column(name = "driver_grade")
	public String getDriverGrade() {
		return this.driverGrade;
	}

	public void setDriverGrade(String driverGrade) {
		this.driverGrade = driverGrade;
	}

	@Column(name = "driver_state")
	public String getDriverState() {
		return this.driverState;
	}

	public void setDriverState(String driverState) {
		this.driverState = driverState;
	}

	@Column(name = "driver_notice")
	public String getDriverNotice() {
		return this.driverNotice;
	}

	public void setDriverNotice(String driverNotice) {
		this.driverNotice = driverNotice;
	}

	@Column(name = "driver_tel")
	public Integer getDriverTel() {
		return this.driverTel;
	}

	public void setDriverTel(Integer driverTel) {
		this.driverTel = driverTel;
	}

}
