package com.ggsleeper.bean;

// Generated 2017-5-23 14:43:51 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblRolePrivilege generated by hbm2java
 */
@Entity
@Table(name = "tbl_role_privilege", catalog = "carmanager")
public class RolePrivilege implements java.io.Serializable {

	private Integer id;
	private Integer roleId;
	private Integer priId;

	public RolePrivilege() {
	}

	public RolePrivilege(Integer roleId, Integer priId) {
		this.roleId = roleId;
		this.priId = priId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ROLE_ID")
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@Column(name = "PRI_ID")
	public Integer getPriId() {
		return this.priId;
	}

	public void setPriId(Integer priId) {
		this.priId = priId;
	}

}
