package com.ggsleeper.bean;

// Generated 2017-5-23 23:51:33 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Runbackinfo generated by hbm2java
 */
@Entity
@Table(name = "tbl_runbackinfo", catalog = "carmanager")
public class Runbackinfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String carlpn;
	private String drivername;
	private String runTime;
	private String backTime;
	private String infostate;

	public Runbackinfo() {
	}

	public Runbackinfo(String carlpn, String drivername, String runTime,
			String backTime, String infostate) {
		this.carlpn = carlpn;
		this.drivername = drivername;
		this.runTime = runTime;
		this.backTime = backTime;
		this.infostate = infostate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "carlpn")
	public String getCarlpn() {
		return this.carlpn;
	}

	public void setCarlpn(String carlpn) {
		this.carlpn = carlpn;
	}

	@Column(name = "drivername")
	public String getDrivername() {
		return this.drivername;
	}

	public void setDrivername(String drivername) {
		this.drivername = drivername;
	}

	@Column(name = "runTime")
	public String getRunTime() {
		return this.runTime;
	}

	public void setRunTime(String runTime) {
		this.runTime = runTime;
	}

	@Column(name = "backTime")
	public String getBackTime() {
		return this.backTime;
	}

	public void setBackTime(String backTime) {
		this.backTime = backTime;
	}

	@Column(name = "infostate")
	public String getInfostate() {
		return this.infostate;
	}

	public void setInfostate(String infostate) {
		this.infostate = infostate;
	}

}
