package com.ggsleeper.bean;

// Generated 2017-5-24 11:37:04 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblUser generated by hbm2java
 */
@Entity
@Table(name = "tbl_user", catalog = "carmanager")
public class User implements java.io.Serializable {

	private Integer userId;
	private String loginName;
	private String userPasswd;
	private String name;
	private String job;
	private String userTel;
	private String userIssue;

	public User() {
	}

	public User(String loginName, String userPasswd, String name,
			String job, String userTel,String userIssue) {
		this.loginName = loginName;
		this.userPasswd = userPasswd;
		this.name = name;
		this.job = job;
		this.userTel = userTel;
		this.userIssue=userIssue;
	}

	

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "USER_ID", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "LOGIN_NAME")
	public String getLoginName() {
		return this.loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	@Column(name = "USER_PASSWD")
	public String getUserPasswd() {
		return this.userPasswd;
	}

	public void setUserPasswd(String userPasswd) {
		this.userPasswd = userPasswd;
	}

	@Column(name = "NAME")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "JOB")
	public String getJob() {
		return this.job;
	}

	public void setJob(String job) {
		this.job = job;
	}

	@Column(name = "USER_TEl")
	public String getUserTel() {
		return this.userTel;
	}

	public void setUserTel(String userTel) {
		this.userTel = userTel;
	}
	@Column(name = "USER_ISSUE")
	public String getUserIssue() {
		return userIssue;
	}

	public void setUserIssue(String userIssue) {
		this.userIssue = userIssue;
	}

}
